name:                LtuPatternFactory
version:             0.1.0.0
synopsis:            Comparing OO Design Patterns with Functional Programming concepts
homepage:            https://github.com/thma/LtuPatternFactory#readme
github:              "thma/LtuPatternFactory"
license:             Apache-2.0
license-file:        LICENSE
author:              Thomas Mahler
maintainer:          thma@apache.org
copyright:           2018 - 2021 Thomas Mahler
category:            Programming
#build-type:          Simple
#cabal-version:       >=1.10
extra-source-files:  README.md
description:         Please see the README on GitHub at <https://github.com/thma/LtuPatternFactory#readme>



dependencies:
- base >= 4.7 && < 5

executables:
  LtuPatternFactory:
    main:                Main.hs
    source-dirs:         src
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
    dependencies:
#    - LtuPatternFactory
    - containers
    - mtl
    - aeson
    - aeson-pretty
    - text
    - directory
    - bytestring
    - tagged
    - cmark-gfm
    - cheapskate
    - blaze-html
    - parallel
    - comonad
    - time
    - zlib

tests:
  LtuPatternFactory-test:
    main:                Main.hs
    source-dirs:         src
 #   ghc-options:
 #   - -threaded
 #   - -rtsopts
 #   - -with-rtsopts=-N
    dependencies:
#    - LtuPatternFactory
    - containers
    - mtl
    - aeson
    - aeson-pretty
    - text
    - directory
    - bytestring
    - tagged
    - cmark-gfm
    - cheapskate
    - blaze-html
    - parallel
    - comonad
    - zlib
